{levelname} {asctime} {module} {process:d} {thread:d} {message}
{levelname} {asctime} {module} {process:d} {thread:d} {message}
{levelname} {asctime} {module} {process:d} {thread:d} {message}
{levelname} {asctime} {module} {process:d} {thread:d} {message}
{levelname} {asctime} {module} {process:d} {thread:d} {message}
Traceback (most recent call last):
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 199, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'myTaste.django_session' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 249, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 220, in inner
    if not self.has_permission(request):
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 194, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/utils/functional.py", line 360, in _setup
    self._wrapped = self._setupfunc()
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 173, in get_user
    user_id = _get_user_session_key(request)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 58, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 64, in __getitem__
    return self._session[key]
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 204, in _get_session
    self._session_cache = self.load()
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/gaoi/.virtualenvs/mytaste/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'myTaste.django_session' doesn't exist")
{levelname} {asctime} {module} {process:d} {thread:d} {message}
